### PR TITLE
Added unicode support for PySpark session.

### PR DESCRIPTION
**Pull request by alex-the-man**

### CODE REVIEW

**Comment by aggFTW** [comment]
Unit tests?

**Comment by aggFTW** [comment]
LGTM otherwise.

**Comment by aggFTW** [comment]
@msftristew

**Comment by linchan825** [comment]
Can we comment the code with a little explanation on why this extra handling is needed?

**Comment by msftristew** [comment]
@linchan-ms Why did you close this?

LGTM

**Comment by linchan825** [comment]
Sorry, I mean to comment only but somehow clicked the wrong button.

**Comment by msftristew** [comment]
Has this been tested to verify it resolves the Unicode-related issues we've been seeing w/ Sparkmagic?

**Comment by alex-the-man** [comment]
Yes and I'm porting this fix to cloudera's branch. (We are upstreaming all our chnages)
In that PR, unit test is included.

**Pull request merged**
